spring:
  r2dbc:
    password: root
    username: root
    url: r2dbc:postgresql://localhost:5433/postgres?schema=anime
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
